# Makefile for compiling and running code with different variable values

# Compiler
CC = gcc

# Compiler flags
CFLAGS = -fopenmp -g

# Source file
SRC = omp_homework.c

# Executable name
EXEC = omp_homework

# Variable values
N = 1000 10000 30000
num_threads = 1 2 4 6 8 12 16 20 24

# Define all combinations of variable values
ALL_COMBINATIONS := $(foreach v1,$(N),$(foreach v2,$(num_threads),$(v1)_$(v2)))

# Define targets for each combination of variable values
all: $(addprefix run_,$(ALL_COMBINATIONS))

# Rule to compile and link executable with specific variable values
$(EXEC)_%: $(SRC)
    $(CC) $(CFLAGS) -DVAR1=$(word 1,$(subst _, ,$*)) -DVAR2=$(word 2,$(subst _, ,$*)) $(SRC) -o $@

# Rule to run the executable
run_%: $(EXEC)_% 
    ./$< $(word 1,$(subst _, ,$*)) $(word 2,$(subst _, ,$*))

# Clean rule
clean:
    rm -f $(EXEC)_* $(EXEC)
